{:title "Configure Git"
 :layout :page
 :page-index 2
 :section "Overview"}


Configure Git page

=== Core configuration


.Configure your Git identity
[source,shell]
----
git config --global user.email=obfuscated-name@github.com
git config -- global user.name="Practicalli John"
----

==== username and email

==== using obfuscated email address

==== Global Ignore file

Add patterns that should be ignnored across all projects, such as editor specific configurations and operating system backup files

Example global-git-ignore file

=== Clojure code example




.Clojure code syntax highlighting example
[source,clojure]
----
(defn example-function
  "This is a very simple doc string"
  [arguments]
  (map inc arguments))
----

=== ssh keys

generate an SSH key with `ssh-keygen -t rsa -C email-name@domain.com`

==== provide a longish passphrase

TIP:  Use an actual phrase or a series of random words with spaces
TIP: store the passphrase in the keyring of the operating system, and have it unlock the key when you login



=== Developer token
- for use with other tools such as Emacs Magit
